name: Automated Version Bump
description: Automated version bump for npm packages.
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: chevron-up
  color: blue
inputs:
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: ''
    required: false
