name: Pull Request Test

# This workflow runs the action every time you push to a PR to allow for easy testing of the github-facing side of this project. Commit and push are skipped so no changes will be made to the branch. The new version will be shown on the github run page.

on:
  pull_request:

env:
  minor: 'MINOR_VERSION'
  major: 'MAJOR_VERSION'

jobs:
  test:
    name: 'Pull Request Test'
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'

      - name: 'Checkout action in test dir'
        uses: 'actions/checkout@v4'
        with:
          path: .github/test

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'npm version'
        run: npm -v

      - name: 'Automated Version Bump'
        id: version-bump
        uses: './.github/test'
        with:
          minor-wording: ${{ env.minor }}
          major-wording: ${{ env.major }}
          skip-commit: 'true'
          skip-push: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json

  report:
    name: 'Report'
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: 'Summary'
        env:
          RESULT: ${{ needs.test.result }}
          NEW_TAG: "${{ needs.test.outputs.new_tag }}"
        run: |
          echo "### Pull Request Test Report" >> $GITHUB_STEP_SUMMARY
          
          if [[ $RESULT == "success" ]]; then
            status="Success"
          else
            status="Failure"
          fi
          
          echo "Status: \`$status\`" >> $GITHUB_STEP_SUMMARY
          echo "New Version: \`$NEW_TAG\`" >> $GITHUB_STEP_SUMMARY
