name: Confirm Pull Request

on:
  pull_request:

jobs:
  end-to-end-tests:
    name: Conduct end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        name: Install dependencies
      - run: npm run end-to-end-test
